if(NOT DEFINED SOURCE_FILE OR NOT DEFINED DESTINATION_FILE)
    message(FATAL_ERROR "SOURCE_FILE and DESTINATION_FILE are required.")
endif()

if(NOT EXISTS "${SOURCE_FILE}")
    message(FATAL_ERROR "Source file does not exist: ${SOURCE_FILE}")
endif()

if(NOT EXISTS "${DESTINATION_FILE}")
    get_filename_component(DESTINATION_DIRECTORY "${DESTINATION_FILE}" DIRECTORY)
    file(MAKE_DIRECTORY "${DESTINATION_DIRECTORY}")
    file(COPY_FILE "${SOURCE_FILE}" "${DESTINATION_FILE}" ONLY_IF_DIFFERENT)
endif()
